tasks:
  - init: |
      pyenv install 3.10.7
      poetry env use /workspace/.pyenv_mirror/fakeroot/versions/3.10.7/bin/python
      poetry install
      source "$(poetry env info -p)/bin/activate"
      pre-commit install
      pre-commit
